[project]
name = "clickshare-temperature"
version = "0.1.0"
description = "Gather temperature readings from Barco ClickShare devices"
readme = "README.md"
license = "MIT"
authors = [
    { name = "nocarryr", email = "matt@nomadic-recording.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
    "click>=8.3.3",
    "click-extra>=8.2.0",
    "python-dotenv>=1.2.2",
    "tzdata>=2026.2 ; sys_platform == 'win32'",
    "yarl>=1.23.0",
]

[project.scripts]
clickshare-temperature = "clickshare_temperature:main"

[project.optional-dependencies]
orm = [
    "sqlalchemy>=2.1.1",
    "sqlalchemy-utc>=0.14.0",
]
influx = [
    "influxdb3-python>=0.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.mypy]
mypy_path = ["typings"]
packages = ["clickshare_temperature"]

[[tool.mypy.overrides]]
module = "influxdb_client_3.*"
ignore_errors = true

[tool.ruff]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]

[tool.pytest]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "mypy>=1.20.2",
    "ruff>=0.15.12",
    "pytest>=9.0.3",
    "pytest-codspeed>=5.0.3",
    "pytest-httpserver>=1.1.5",
]
